config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :only => [:index, :show]
  resources :charges, only: [:new, :create]
  resources :wikis 
  resources :wikis do
    resources :collaborators 
  end
  

  get 'collaborators/:id', to: 'collaborators#show'
  #delete 'collaborators/destroy'
  delete 'charges/downgrade'

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/amount.rb
class Amount < ApplicationRecord
  belongs_to :charges 

  def default
    15_00
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
#class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user

  validates :user_id, uniqueness: { scope: :wiki_id }
end

app/models/collaborators.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user

  validates :user_id, uniqueness: { scope: :wiki_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :wikis, through: :collaborators, dependent: :destroy

  before_save { self.role ||= :standard_member }

  enum role: [:standard_member, :premium_member, :admin]

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user

  after_initialize :init
  def init
    self.private = false if (self.has_attribute? :private) && self.private.nil?
  end

  #default_scope { order('rank DESC') }

  has_many :collaborators
  has_many :users, through: :collaborators 
  has_many :users, through: :collaborators, dependent: :destroy 

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true  
  #validates :user, presence: true 

  def set_default_privacy
    self.private ||= false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit 
  protect_from_forgery 
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :encrypted_password, :remember_me, :login, :user]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController 

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: 15_00
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
 
    charge = Stripe::Charge.create(
      customer: customer.id, 
      amount: 15_00,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attribute(:role, 'premium_member')
 
    flash[:notice] = "Your transaction has been approved, #{current_user.email}! You are now a Premium Member of Blocipedia."
    redirect_to root_path(current_user) 

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def downgrade
    current_user.update_attribute(:role, 'standard_member')
    current_user.wikis.update_all(private: false)
    
    flash[:notice] = "Your account has been changed back to a standard free membership."
    redirect_to new_charge_path 
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @collaborators = @wiki.collaborators.all
  end
  
  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by_email(params[:collaborator][:user])
    @collaborator = Collaborator.new

    if @user == nil
      flash[:error] = "That user could not be found."
      return redirect_to edit_wiki_path(@wiki)
    else
      @collaborator.wiki = @wiki
      @collaborator.user = @user 
    end

    if @collaborator.save
      flash[:notice] = "Collaborator added."
      return redirect_to @wiki
    else
      flash[:alert] = "Error occured. Please try again."
      return redirect_to @wiki
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator has been removed."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:alert] = "There was an error removing this collaborator. Please try again."
      redirect_to edit_wiki_path(@wiki)
    end
  end

  private

  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    @private_wikis = @user.wikis.where(private: true)

    if @user.role == 'premium'
      @user.role = 'standard'
      @user.premium = false
      @user.standard = true
      @private_wikis.update_all(private: false)
    end
    
    if @user.save
      flash[:notice] = "User was updated."
    else
      flash.now[:alert] = "There was an error updating the user. Please try again."
      render :edit
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])

  end

  def new
    @wiki = Wiki.new 
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators.all
  end

  def create
    @wiki = Wiki.new
    @wiki.user = current_user
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    if @wiki.user.standard_member?
      @wiki.private = false 
    end

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki 
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new 
    end
  end

  def update 
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    if current_user.premium_member? || current_user.admin?
      @wiki.private = params[:wiki][:private]
    end

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki 
    else
      flash.now[:alert] = "There was an error updating this wiki. Please try again."
      render :edit 
    end
  end

  def destroy 
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "Your wiki, \"#{@wiki.title}\", was deleted successfully."
      redirect_to wikis_path 
    else
      flash.now[:alert] = "There was an error deleting this wiki. Please try again."
      render :show 
    end
  end
  
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  def markdown(text)
    options = {
      hard_wrap: true,
      filter_html: true
    }
    extensions = { 
      autolink: true, 
      no_intraemphasis: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def private_wikis?(current_user)
    current_user.premium? || current_user.admin?
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <% if current_user.role == 'standard_member' %>
    <h3>Click below to upgrade to a Premium account!</h3>
    <p>Premium accounts are $15 and will allow you to post private wikis!</p>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% else %>
    <h3>Click below to downgrade back to a Standard account.</h3>
    <p>You will lose your ability to create or view private wikis and all of your private wikis will become public</p>
    <button><%= link_to 'Downgrade', charges_downgrade_path, method: :delete %></button>
  <% end %>
<% end %>

app/views/collaborators/edit.html.erb
<%= form_for ([@wiki, @collaborator]) do |f| %>
  <div class="form-group">
    <%= f.label :user %>
    <%= f.text_field :user, class: 'form-control', placeholder: "Enter User Email", as: :fake %>
    <%= submit_tag "Delete", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/collaborators/index.html.erb
<% @collaborators.each do |collaborator| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= collaborator.user.email %>
      </h4>
    </div>
  </div>
<% end %>

app/views/collaborators/new.html.erb
<%= form_for ([@wiki, @collaborator]) do |f| %>
  <div class="form-group">
    <%= f.label :user %>
    <%= f.text_field :user, class: 'form-control', placeholder: "Enter User Email", as: :fake %>
    <%= submit_tag "Add", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if user_signed_in? %>
    Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
COMING SOON.

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia!</h1>
<p><%= link_to "View Wikis", wikis_path, class: 'btn btn-success' %></p>

  <div class="upgrade">
    <% if current_user.role == 'standard_member'%>
      <p>Want to get more out of Blocipedia? Find out about our PREMIUM MEMBERSHIPS below!</p>
      <%= button_to "Click Me!", charges_path %>
    <% end %>
  </div>

  <div class="downgrade">
    <% if current_user.role == 'premium_member'%>
      <p>Not enjoying your Premium membership? Click below to downgrade.</p>
      <%= button_to "Are you sure you want to Click Me?", charges_path %>
    <% end %>
  </div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium_member? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Make this Private?
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Don't just make stuff up! We'll find out.</li>
      <li>Keep it PG-13.</li>
      <li>No Pepe memes. Talking about Pepe will result in an automatic ban.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
        <% if current_user.admin? || current_user.premium_member? %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Make this Private?
            <% end %>
          </div>
        <% end %>
    <% end %>
    <% if current_user.premium_member? %>
      Add Collaborators? <%= link_to "CLICK HERE!", new_wiki_collaborator_path(@wiki) %>
      <p>---</p>
      <% @collaborators.each do |collaborator| %>
      <p>Current Collaborators:</p>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= collaborator.user.email %> <%= link_to "Delete?", wiki_collaborator_path(@wiki, collaborator), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this collaborator?'} %>
            </h4>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<p><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %></p>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Don't just make stuff up! We'll find out.</li>
      <li>Keep it PG-13.</li>
      <li>No Pepe memes. Talking about Pepe will result in an automatic ban.</li>
      <li>NEW FEATURE: PREMIUM USERS may now add COLLABORATORS to their wikis! Just click the "Edit" button after you've created your wiki to be taken to the form to add collaborators!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>

    <%= render "wikis/form", f: f %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
 
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>